// examples/with-solid-start/src/app.tsx
import { Router, action, query } from '@solidjs/router';
import { FileRoutes } from '@solidjs/start/router';
import { Suspense } from 'solid-js';
import {
  createClient,
  Provider,
  cacheExchange,
  fetchExchange,
} from '@m1212e/urql-solid-start';

const client = createClient({
  url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  exchanges: [cacheExchange, fetchExchange],
});

export default function App() {
  return (
    <Router
      root={props => (
        <Provider value={{ client, query, action }}>
          <Suspense>{props.children}</Suspense>
        </Provider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}

// examples/with-react-native/App.js
import React from 'react';
import { Client, Provider, cacheExchange, fetchExchange } from '@m1212e/urql';

import PokemonList from './src/screens/PokemonList';

const client = new Client({
  url: 'https://trygql.formidable.dev/graphql/basic-pokedex',
  exchanges: [cacheExchange, fetchExchange],
});

const App = () => {
  return (
    <Provider value={client}>
      <PokemonList />
    </Provider>
  );
};

export default App;
